[package]
name = "rustpi"
version = "0.1.0"

[[bin]]
name = "rustpi"
path = "src/main.rs"

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"


[dependencies]
cortex-a = { git = "https://github.com/tonnylyz/cortex-a"}
register = "0.5.0"