name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust nightly toolchain
      uses: actions-rs/toolchain@v1.0.6
      with: 
        toolchain: nightly
        components: rust-src
        override: true
    - name: Build for aarch64
      run: cargo build --target target.aarch64.json -Zbuild-std=core,alloc --release
    - name: Build for riscv64
      run: cargo build --target target.riscv64.json -Zbuild-std=core,alloc --release
